name: CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        ocaml: [4.11.2, 4.14.2]
        python: ['3.7', '3.9', '3.11']

    steps:
    - uses: actions/checkout@v4
    - name: Setup opam and OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml }}
    - name: Install num
      if: ${{ matrix.ocaml >= '4.06' }}
      run: opam install -y num
    - name: Set up Python for tests (and gelpia)
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install Python dependencies
      run: |
        if [ "${{ matrix.python }}" = "3.7" ]; then
          python -m pip install --upgrade "pip<24.1" "setuptools<69" wheel
        else
          python -m pip install --upgrade pip setuptools wheel
        fi
        pip install pyyaml
    - name: Install gelpia dependencies
      run: |
        pip install sly
        sudo apt install flex bison wget
    - name: Download and build gelpia
      env:
        CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
      run: |
        git clone https://github.com/meelgroup/gelpia.git
        cd gelpia
        git checkout develop
        make requirements
        make
    - name: Build FPTaylor
      run: opam exec -- make
    - name: Run basic tests
      run: |
        grep opt -C 3 default.cfg
        opam exec -- make test
    - name: Run basic tests with gelpia
      run: |
        sed -i "s|^opt = bb|opt = gelpia|g" default.cfg
        opam exec -- make test
    - name: Regression tests
      run: |
        cd scripts
        opam exec -- python run_tests.py ../tests/basic
        opam exec -- python run_tests.py ../tests/micro
        opam exec -- python run_tests.py ../tests/core
